### ISSUE TITLE
fix: 일부 직업데이터 정정 요청

### ISSUE THREAD

**Issue by wn-na** [Aboa123/maple-home#1]
**제로** 
 - 코강난이도 
   - 최상
   > 2중 7코의 직업...
 - 유틸리티
   - 3 -> 4
   > 크바는 신이야! 

**불독**
 - 보스등급 
   - 5 -> 2 
   > ???: 불독 쌔요. 최소 3초쿨뚝에, 유니온 8천에 언스 만렙에 도퍼노바이프 만렙찍고, 벞지 한줄뽑으면되요! 크확도 100퍼하구요
   
**히어로**
 - 유틸 
   - 3 -> 4
   > 5차 기준 무적기 25초

**윈드브레이커**
- 자본
  - 고자본 -> 저자본
  > 무난한 직업의 대명사중 하나

**메카닉**
- 유틸리티
  - 2 -> 4
  > 파티기준 행복사 할정도의 유틸 소유

**아델**
- 조작 난이도
  - 1 -> 3
  > 무지성 디바이드는 쉬우나, 스택관리를 시작하면 어려운 캐릭터

**Comment by Aboa123** [comment]
반영하겠습니다! 감사합니다!
